version: '3.7'

services:
  web:
    build:
      context: ./adirect
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:80 run
    ports:
      - '80:80'
    volumes:
      - '/home/qwil/testversion1/adirect/app/static'
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    tty: true
  
    ports:
      - '5000:5000'

